[package]
name = "vfs-easy"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vfs"
path = "src/main.rs"

[[bin]]
name = "vfsd"
path = "src/vfsd.rs"

[dependencies]
chrono = "0.4.41"
bincode = "2.0.1"
serde = { version = "1.0.219", features = ["derive"] }
